version: "3.3"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
    # env_file:
    #   ./.env
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-db:/data/techwondoe_round_1

volumes:
  mongo-db:
